
version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: breast_cancer_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: breast_cancer_ui
    ports:
      - "8501:8501"
    environment:
      API_URL: "http://api:8000/predict"
    depends_on:
      - api
    restart: unless-stopped
